POST https://j9ecfdqhul.execute-api.us-east-1.amazonaws.com/dev/services/carwash/create
Content-Type: application/json
Authorization: Bearer <id_token>

{
  "name": "Downtown Car Wash",
  "services": {
    "basic": {
      "name": "Basic Wash",
      "price": 25,
      "duration": 30
    },
    "deluxe": {
      "name": "Deluxe Wash",
      "price": 35,
      "duration": 45
    }
  },
  "address": "123 Main St, Anytown, USA",
  "hasElectricPlant": true,
  "hasIndividualWomenBathroom": true,
  "hasIndividualManBathroom": true
}
