POST https://ksbmzzwjul.execute-api.us-east-1.amazonaws.com/dev/users/verify-otp
Content-Type: application/json

{
  "username": "uribesotod@gmail.com",
  "session": "AYABeAsfvq_YPLx0q0BtOiW8r0UAHQABAAdTZXJ2aWNlABBDb2duaXRvVXNlclBvb2xzAAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOnVzLWVhc3QtMTo3NDU2MjM0Njc1NTU6a2V5L2IxNTVhZmNhLWJmMjktNGVlZC1hZmQ4LWE5ZTA5MzY1M2RiZQC4AQIBAHjHL4WD3WpekpFe85nxP9Nwg99u3bPN6BTSaB-uHZcTLAFsZDpimx34QQBZX6sWxkZTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXYTm2hcnrGbybqZdAgEQgDsbvTdlF4lVKYtSHiLHo2coN4PkLWKzgWtcZ1iha0-7i6FYOiYTL-8l2EW3c-FwrPIqLpGS3AqzptQJQgIAAAAADAAAEAAAAAAAAAAAAAAAAAADgtjlIT6yyJh3_uz76Vjj_____wAAAAEAAAAAAAAAAAAAAAEAAADv_IaTE3oXzq4FlIu-RrUBc95LpGKJ2A9tCrGBL3BkDVGWBFo9L2IdChPfd-T5L4hZWhrl_uI2ff6ZiwWSU3IndUv2qqBDNxscjMPTuXkUiI0cCQWGGOf6lBQN1K0UOgI12Hw4vqOrZ73TpchTdow7Pkj27V7ikVOkJ3e_5bfdibunL4loEmfqzO7Fewg5JDMx9J0RCFBxrkd1ee1EBF3CCdcMca1RdcVBLNcSp2GGlEdCvsH8SbuyXDE6wziFhJiRwVeMq25-rZAte8a4hbP2GtLvUwE9jQqXS6Y5yRIbXO9cBUEy689w4TT0oDzDjblt9zFr_GbgzAVIgqrjs2rE",
  "otp": "370539"
}
