name: Deploy to S3

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code at specific tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Zip the build output
        run: cd dist && zip -r code.zip ./*

      - name: Create S3 Bucket if it doesn't exist
        id: create-bucket
        run: |
          if ! aws s3 ls "s3://${{ secrets.S3_BUCKET_NAME }}" ; then
            aws s3 mb "s3://${{ secrets.S3_BUCKET_NAME }}"
            echo "Created S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
          else
            echo "S3 bucket already exists: ${{ secrets.S3_BUCKET_NAME }}"
          fi

      - name: Upload code ZIP to S3
        run: aws s3 cp dist/code.zip s3://${{ secrets.S3_BUCKET_NAME }}/services-api/code.zip
